name: Terraform Lint & Validate
on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform-lint.yml"

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

      - name: TFLint
        run: tflint --init

      - name: TFLint lint
        run: tflint
